# Generated by Django 2.2.11 on 2021-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='blocker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
