# Generated by Django 2.2.11 on 2021-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210810_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='typing1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='typing2',
            field=models.BooleanField(default=False),
        ),
    ]
