# Generated by Django 2.2.11 on 2021-08-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_me_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.TextField(null=True),
        ),
    ]
