# Generated by Django 2.2.11 on 2021-08-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_message_replier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='replier',
            new_name='replied',
        ),
    ]
