# Generated by Django 2.2.11 on 2021-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210817_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rtype',
            field=models.TextField(null=True),
        ),
    ]
