# Generated by Django 2.2.11 on 2021-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210825_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='offer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
