# Generated by Django 2.2.11 on 2021-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_chat_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
