# Generated by Django 2.2.11 on 2021-09-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_chat_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
    ]
